#############################################################################
# Makefile for building: brewberryPi_v2.app/Contents/MacOS/brewberryPi_v2
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  brewberryPi_v2.pro
# Template: app
# Command: /opt/Qt/5.15.2/clang_64/bin/qmake -o Makefile brewberryPi_v2.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug CONFIG+=force_debug_info CONFIG+=separate_debug_info
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Library/Developer/CommandLineTools/usr/bin/clang
CXX           = /Library/Developer/CommandLineTools/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_QUICK_LIB -DQT_CHARTS_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCharts.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQmlModels.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtXml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I. -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/AGL.framework/Headers -I/opt/Qt/5.15.2/clang_64/mkspecs/macx-clang -F/opt/Qt/5.15.2/clang_64/lib
QMAKE         = /opt/Qt/5.15.2/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/Qt/5.15.2/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/Qt/5.15.2/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = brewberryPi_v21.0.0
DISTDIR = /Users/cradoumis/Documents/Brewery/brewberryPi_Public/.tmp/brewberryPi_v21.0.0
LINK          = /Library/Developer/CommandLineTools/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/opt/Qt/5.15.2/clang_64/lib
LIBS          = $(SUBLIBS) -F/opt/Qt/5.15.2/clang_64/lib -m32 -Wall -framework QtQuick -framework QtCharts -framework QtOpenGL -framework QtWidgets -framework QtGui -framework AppKit -framework Metal -framework QtQmlModels -framework QtQml -framework QtWebSockets -framework QtNetwork -framework QtXml -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Library/Developer/CommandLineTools/usr/bin/ar cq
RANLIB        = /Library/Developer/CommandLineTools/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = brewinggraph.cpp \
		countdowntimer.cpp \
		main.cpp \
		max31865.cpp \
		pidcontroller.cpp \
		radialbar.cpp \
		rpicomms.cpp \
		rpidata.cpp \
		rpithreads.cpp \
		websocket.cpp \
		pigpio.cpp qrc_qml.cpp \
		moc_brewinggraph.cpp \
		moc_countdowntimer.cpp \
		moc_radialbar.cpp \
		moc_rpidata.cpp \
		moc_rpithreads.cpp \
		moc_websocket.cpp
OBJECTS       = brewinggraph.o \
		countdowntimer.o \
		main.o \
		max31865.o \
		pidcontroller.o \
		radialbar.o \
		rpicomms.o \
		rpidata.o \
		rpithreads.o \
		websocket.o \
		pigpio.o \
		qrc_qml.o \
		moc_brewinggraph.o \
		moc_countdowntimer.o \
		moc_radialbar.o \
		moc_rpidata.o \
		moc_rpithreads.o \
		moc_websocket.o
DIST          = /opt/Qt/5.15.2/clang_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/qdevice.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/device_config.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/unix.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/mac.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/macx.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/sanitize.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/clang.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/clang-mac.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/qconfig.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/macx-clang/qmake.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/spec_post.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/sdk.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/toolchain.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/toolchain.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/default_pre.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/default_post.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/objective_c.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/resolve_target.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/unix/separate_debug_info.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/qml_debug.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/mac.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/qt.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/resources_functions.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/resources.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/moc.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/uic.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/qmake_use.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/file_copies.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/rez.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/lex.prf \
		brewberryPi_v2.pro brewinggraph.h \
		countdowntimer.h \
		max31865.h \
		pidcontroller.h \
		radialbar.h \
		rpicomms.h \
		rpidata.h \
		rpithreads.h \
		websocket.h \
		pigpio.h brewinggraph.cpp \
		countdowntimer.cpp \
		main.cpp \
		max31865.cpp \
		pidcontroller.cpp \
		radialbar.cpp \
		rpicomms.cpp \
		rpidata.cpp \
		rpithreads.cpp \
		websocket.cpp \
		pigpio.cpp
QMAKE_TARGET  = brewberryPi_v2
DESTDIR       = 
TARGET        = brewberryPi_v2.app/Contents/MacOS/brewberryPi_v2

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 13.0
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Library/Developer/CommandLineTools
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/cradoumis/Documents/Brewery/brewberryPi_Public/brewberryPi_v2.pro


include /opt/Qt/5.15.2/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

brewberryPi_v2.app/Contents/MacOS/brewberryPi_v2:  $(OBJECTS)  
	@test -d brewberryPi_v2.app/Contents/MacOS/ || mkdir -p brewberryPi_v2.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	mkdir -p /Users/cradoumis/Documents/Brewery/brewberryPi_Public/brewberryPi_v2.app.dSYM/Contents/Resources/DWARF && dsymutil brewberryPi_v2.app/Contents/MacOS/brewberryPi_v2 --flat -o brewberryPi_v2.app.dSYM/Contents/Resources/DWARF/brewberryPi_v2 && strip -S brewberryPi_v2.app/Contents/MacOS/brewberryPi_v2

Makefile: brewberryPi_v2.pro /opt/Qt/5.15.2/clang_64/mkspecs/macx-clang/qmake.conf /opt/Qt/5.15.2/clang_64/mkspecs/features/spec_pre.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/qdevice.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/device_config.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/unix.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/mac.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/macx.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/sanitize.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/gcc-base.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/gcc-base-mac.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/clang.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/common/clang-mac.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/qconfig.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_charts.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/qt_functions.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/qt_config.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/macx-clang/qmake.conf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/spec_post.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/sdk.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/toolchain.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/toolchain.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/default_pre.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/default_pre.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/resolve_config.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/default_post.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/default_post.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/objective_c.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/resolve_target.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/unix/separate_debug_info.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/qml_debug.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/mac.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/warn_on.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/qt.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/resources_functions.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/resources.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/moc.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/unix/opengl.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/uic.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/unix/thread.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/qmake_use.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/file_copies.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/rez.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/testcase_targets.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/exceptions.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/yacc.prf \
		/opt/Qt/5.15.2/clang_64/mkspecs/features/lex.prf \
		brewberryPi_v2.pro \
		/opt/Qt/5.15.2/clang_64/mkspecs/macx-clang/Info.plist.dSYM.in \
		qml.qrc \
		/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Resources/QtQuick.prl \
		/opt/Qt/5.15.2/clang_64/lib/QtCharts.framework/Resources/QtCharts.prl \
		/opt/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl \
		/opt/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl \
		/opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl \
		/opt/Qt/5.15.2/clang_64/lib/QtQmlModels.framework/Resources/QtQmlModels.prl \
		/opt/Qt/5.15.2/clang_64/lib/QtQml.framework/Resources/QtQml.prl \
		/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Resources/QtWebSockets.prl \
		/opt/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Resources/QtNetwork.prl \
		/opt/Qt/5.15.2/clang_64/lib/QtXml.framework/Resources/QtXml.prl \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl
	$(QMAKE) -o Makefile brewberryPi_v2.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug CONFIG+=force_debug_info CONFIG+=separate_debug_info
/opt/Qt/5.15.2/clang_64/mkspecs/features/spec_pre.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/qdevice.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/features/device_config.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/common/unix.conf:
/opt/Qt/5.15.2/clang_64/mkspecs/common/mac.conf:
/opt/Qt/5.15.2/clang_64/mkspecs/common/macx.conf:
/opt/Qt/5.15.2/clang_64/mkspecs/common/sanitize.conf:
/opt/Qt/5.15.2/clang_64/mkspecs/common/gcc-base.conf:
/opt/Qt/5.15.2/clang_64/mkspecs/common/gcc-base-mac.conf:
/opt/Qt/5.15.2/clang_64/mkspecs/common/clang.conf:
/opt/Qt/5.15.2/clang_64/mkspecs/common/clang-mac.conf:
/opt/Qt/5.15.2/clang_64/mkspecs/qconfig.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_charts.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt/5.15.2/clang_64/mkspecs/features/qt_functions.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/qt_config.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/macx-clang/qmake.conf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/spec_post.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/exclusive_builds.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/sdk.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/toolchain.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/toolchain.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/default_pre.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/default_pre.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/resolve_config.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/default_post.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/default_post.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/objective_c.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/resolve_target.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/unix/separate_debug_info.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/qml_debug.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/mac.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/warn_on.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/qt.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/resources_functions.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/resources.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/moc.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/unix/opengl.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/uic.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/unix/thread.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/qmake_use.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/file_copies.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/rez.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/mac/asset_catalogs.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/testcase_targets.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/exceptions.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/yacc.prf:
/opt/Qt/5.15.2/clang_64/mkspecs/features/lex.prf:
brewberryPi_v2.pro:
/opt/Qt/5.15.2/clang_64/mkspecs/macx-clang/Info.plist.dSYM.in:
qml.qrc:
/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Resources/QtQuick.prl:
/opt/Qt/5.15.2/clang_64/lib/QtCharts.framework/Resources/QtCharts.prl:
/opt/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Resources/QtOpenGL.prl:
/opt/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Resources/QtWidgets.prl:
/opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Resources/QtGui.prl:
/opt/Qt/5.15.2/clang_64/lib/QtQmlModels.framework/Resources/QtQmlModels.prl:
/opt/Qt/5.15.2/clang_64/lib/QtQml.framework/Resources/QtQml.prl:
/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Resources/QtWebSockets.prl:
/opt/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Resources/QtNetwork.prl:
/opt/Qt/5.15.2/clang_64/lib/QtXml.framework/Resources/QtXml.prl:
/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Resources/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile brewberryPi_v2.pro -spec macx-clang CONFIG+=debug CONFIG+=qml_debug CONFIG+=force_debug_info CONFIG+=separate_debug_info

qmake_all: FORCE

brewberryPi_v2.app/Contents/PkgInfo: 
	@test -d brewberryPi_v2.app/Contents || mkdir -p brewberryPi_v2.app/Contents
	@$(DEL_FILE) brewberryPi_v2.app/Contents/PkgInfo
	@echo "APPL????" > brewberryPi_v2.app/Contents/PkgInfo
brewberryPi_v2.app/Contents/Resources/empty.lproj: 
	@test -d brewberryPi_v2.app/Contents/Resources || mkdir -p brewberryPi_v2.app/Contents/Resources
	@touch brewberryPi_v2.app/Contents/Resources/empty.lproj
	
brewberryPi_v2.app/Contents/Info.plist: 
	@test -d brewberryPi_v2.app/Contents || mkdir -p brewberryPi_v2.app/Contents
	@$(DEL_FILE) brewberryPi_v2.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.yourcompany.brewberryPi-v2,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.yourcompany.brewberryPi-v2,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.13,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,brewberryPi_v2,g" -e "s,@LIBRARY@,brewberryPi_v2,g" -e "s,\$${EXECUTABLE_NAME},brewberryPi_v2,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /opt/Qt/5.15.2/clang_64/mkspecs/macx-clang/Info.plist.app >brewberryPi_v2.app/Contents/Info.plist

all: Makefile \
		brewberryPi_v2.app/Contents/PkgInfo \
		brewberryPi_v2.app/Contents/Resources/empty.lproj \
		brewberryPi_v2.app/Contents/Info.plist brewberryPi_v2.app/Contents/MacOS/brewberryPi_v2

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /opt/Qt/5.15.2/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents brewinggraph.h countdowntimer.h max31865.h pidcontroller.h radialbar.h rpicomms.h rpidata.h rpithreads.h websocket.h pigpio.h $(DISTDIR)/
	$(COPY_FILE) --parents brewinggraph.cpp countdowntimer.cpp main.cpp max31865.cpp pidcontroller.cpp radialbar.cpp rpicomms.cpp rpidata.cpp rpithreads.cpp websocket.cpp pigpio.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r brewberryPi_v2.app
	-$(DEL_FILE) /Users/cradoumis/Documents/Brewery/brewberryPi_Public/brewberryPi_v2.app.dSYM/Contents/Resources/DWARF/brewberryPi_v2 /Users/cradoumis/Documents/Brewery/brewberryPi_Public/brewberryPi_v2.app.dSYM/Contents/Info.plist
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=qml_debug CONFIG+=force_debug_info CONFIG+=separate_debug_info

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		/opt/Qt/5.15.2/clang_64/bin/rcc \
		TemperatureChart.qml \
		Page3Form.qml \
		ToggleButton.qml \
		Page1Form.qml \
		qtquickcontrols2.conf \
		brewberrySplash.qml \
		Page2Form.qml \
		main.qml \
		mainHopsLoadingGreen.png \
		Lower\ Background\ Export.png \
		Grains.png \
		BeerGlass.png \
		Hops.png \
		Yeast.png \
		Pumpkin\ Ale.xml \
		English\ Bitter.xml \
		bjcpStyleGuidelines.json
	/opt/Qt/5.15.2/clang_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/Qt/5.15.2/clang_64/mkspecs/features/data/dummy.cpp
	/Library/Developer/CommandLineTools/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -mmacosx-version-min=10.13 -Wall -Wextra -dM -E -o moc_predefs.h /opt/Qt/5.15.2/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_brewinggraph.cpp moc_countdowntimer.cpp moc_radialbar.cpp moc_rpidata.cpp moc_rpithreads.cpp moc_websocket.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_brewinggraph.cpp moc_countdowntimer.cpp moc_radialbar.cpp moc_rpidata.cpp moc_rpithreads.cpp moc_websocket.cpp
moc_brewinggraph.cpp: brewinggraph.h \
		/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers/QQuickPaintedItem \
		/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers/qquickpainteditem.h \
		moc_predefs.h \
		/opt/Qt/5.15.2/clang_64/bin/moc
	/opt/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/cradoumis/Documents/Brewery/brewberryPi_Public/moc_predefs.h -I/opt/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/cradoumis/Documents/Brewery/brewberryPi_Public -I/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCharts.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQmlModels.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtXml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/Qt/5.15.2/clang_64/lib brewinggraph.h -o moc_brewinggraph.cpp

moc_countdowntimer.cpp: countdowntimer.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTime \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		moc_predefs.h \
		/opt/Qt/5.15.2/clang_64/bin/moc
	/opt/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/cradoumis/Documents/Brewery/brewberryPi_Public/moc_predefs.h -I/opt/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/cradoumis/Documents/Brewery/brewberryPi_Public -I/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCharts.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQmlModels.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtXml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/Qt/5.15.2/clang_64/lib countdowntimer.h -o moc_countdowntimer.cpp

moc_radialbar.cpp: radialbar.h \
		/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers/QQuickPaintedItem \
		/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers/qquickpainteditem.h \
		moc_predefs.h \
		/opt/Qt/5.15.2/clang_64/bin/moc
	/opt/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/cradoumis/Documents/Brewery/brewberryPi_Public/moc_predefs.h -I/opt/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/cradoumis/Documents/Brewery/brewberryPi_Public -I/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCharts.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQmlModels.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtXml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/Qt/5.15.2/clang_64/lib radialbar.h -o moc_radialbar.cpp

moc_rpidata.cpp: rpidata.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		rpicomms.h \
		pigpio.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QThread \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qthread.h \
		moc_predefs.h \
		/opt/Qt/5.15.2/clang_64/bin/moc
	/opt/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/cradoumis/Documents/Brewery/brewberryPi_Public/moc_predefs.h -I/opt/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/cradoumis/Documents/Brewery/brewberryPi_Public -I/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCharts.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQmlModels.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtXml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/Qt/5.15.2/clang_64/lib rpidata.h -o moc_rpidata.cpp

moc_rpithreads.cpp: rpithreads.h \
		rpidata.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		rpicomms.h \
		pigpio.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QThread \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qthread.h \
		max31865.h \
		pidcontroller.h \
		moc_predefs.h \
		/opt/Qt/5.15.2/clang_64/bin/moc
	/opt/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/cradoumis/Documents/Brewery/brewberryPi_Public/moc_predefs.h -I/opt/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/cradoumis/Documents/Brewery/brewberryPi_Public -I/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCharts.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQmlModels.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtXml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/Qt/5.15.2/clang_64/lib rpithreads.h -o moc_rpithreads.cpp

moc_websocket.cpp: websocket.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Headers/QWebSocket \
		/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Headers/qwebsocket.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		rpidata.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		rpicomms.h \
		pigpio.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QThread \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qthread.h \
		moc_predefs.h \
		/opt/Qt/5.15.2/clang_64/bin/moc
	/opt/Qt/5.15.2/clang_64/bin/moc $(DEFINES) --include /Users/cradoumis/Documents/Brewery/brewberryPi_Public/moc_predefs.h -I/opt/Qt/5.15.2/clang_64/mkspecs/macx-clang -I/Users/cradoumis/Documents/Brewery/brewberryPi_Public -I/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCharts.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQmlModels.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtQml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtNetwork.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtXml.framework/Headers -I/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1 -I/Library/Developer/CommandLineTools/usr/lib/clang/14.0.0/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -I/Library/Developer/CommandLineTools/usr/include -F/opt/Qt/5.15.2/clang_64/lib websocket.h -o moc_websocket.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

brewinggraph.o: brewinggraph.cpp brewinggraph.h \
		/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers/QQuickPaintedItem \
		/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers/qquickpainteditem.h \
		/opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers/QPainter \
		/opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brewinggraph.o brewinggraph.cpp

countdowntimer.o: countdowntimer.cpp countdowntimer.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTime \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qtimer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o countdowntimer.o countdowntimer.cpp

main.o: main.cpp /opt/Qt/5.15.2/clang_64/lib/QtQml.framework/Headers/QQmlApplicationEngine \
		/opt/Qt/5.15.2/clang_64/lib/QtQml.framework/Headers/qqmlapplicationengine.h \
		/opt/Qt/5.15.2/clang_64/lib/QtQml.framework/Headers/QQmlContext \
		/opt/Qt/5.15.2/clang_64/lib/QtQml.framework/Headers/qqmlcontext.h \
		/opt/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		/opt/Qt/5.15.2/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers/QQuickWindow \
		/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers/qquickwindow.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QThread \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qthread.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		radialbar.h \
		/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers/QQuickPaintedItem \
		/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers/qquickpainteditem.h \
		brewinggraph.h \
		countdowntimer.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTime \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdatetime.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		rpidata.h \
		rpicomms.h \
		pigpio.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		websocket.h \
		/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Headers/QWebSocket \
		/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Headers/qwebsocket.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		rpithreads.h \
		max31865.h \
		pidcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

max31865.o: max31865.cpp max31865.h \
		rpicomms.h \
		pigpio.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QThread \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o max31865.o max31865.cpp

pidcontroller.o: pidcontroller.cpp pidcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pidcontroller.o pidcontroller.cpp

radialbar.o: radialbar.cpp /opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers/QPainter \
		/opt/Qt/5.15.2/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		radialbar.h \
		/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers/QQuickPaintedItem \
		/opt/Qt/5.15.2/clang_64/lib/QtQuick.framework/Headers/qquickpainteditem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o radialbar.o radialbar.cpp

rpicomms.o: rpicomms.cpp rpicomms.h \
		pigpio.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QThread \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rpicomms.o rpicomms.cpp

rpidata.o: rpidata.cpp rpidata.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		rpicomms.h \
		pigpio.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QThread \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rpidata.o rpidata.cpp

rpithreads.o: rpithreads.cpp rpithreads.h \
		rpidata.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		rpicomms.h \
		pigpio.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QThread \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qthread.h \
		max31865.h \
		pidcontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rpithreads.o rpithreads.cpp

websocket.o: websocket.cpp websocket.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Headers/QWebSocket \
		/opt/Qt/5.15.2/clang_64/lib/QtWebSockets.framework/Headers/qwebsocket.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QJsonObject \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qjsonobject.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QJsonDocument \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qjsondocument.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QTimer \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		rpidata.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QObject \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qobject.h \
		rpicomms.h \
		pigpio.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QThread \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o websocket.o websocket.cpp

pigpio.o: pigpio.cpp pigpio.h \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/QDebug \
		/opt/Qt/5.15.2/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pigpio.o pigpio.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_brewinggraph.o: moc_brewinggraph.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_brewinggraph.o moc_brewinggraph.cpp

moc_countdowntimer.o: moc_countdowntimer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_countdowntimer.o moc_countdowntimer.cpp

moc_radialbar.o: moc_radialbar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_radialbar.o moc_radialbar.cpp

moc_rpidata.o: moc_rpidata.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rpidata.o moc_rpidata.cpp

moc_rpithreads.o: moc_rpithreads.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rpithreads.o moc_rpithreads.cpp

moc_websocket.o: moc_websocket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_websocket.o moc_websocket.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/brewberryPi_v2/bin || mkdir -p $(INSTALL_ROOT)/opt/brewberryPi_v2/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/brewberryPi_v2.app
	
	$(QINSTALL) brewberryPi_v2.app $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/brewberryPi_v2.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/brewberryPi_v2.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/ 


install_debug_info_plist_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/brewberryPi_v2.app.dSYM/Contents || mkdir -p $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/brewberryPi_v2.app.dSYM/Contents
	$(QINSTALL) /Users/cradoumis/Documents/Brewery/brewberryPi_Public/brewberryPi_v2.app.dSYM/Contents/Info.plist $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/brewberryPi_v2.app.dSYM/Contents/Info.plist

uninstall_debug_info_plist_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/brewberryPi_v2.app.dSYM/Contents/Info.plist
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/brewberryPi_v2.app.dSYM/Contents/ 


install_debug_info_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/brewberryPi_v2.app.dSYM/Contents/Resources/DWARF || mkdir -p $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/brewberryPi_v2.app.dSYM/Contents/Resources/DWARF
	$(QINSTALL) /Users/cradoumis/Documents/Brewery/brewberryPi_Public/brewberryPi_v2.app.dSYM/Contents/Resources/DWARF/brewberryPi_v2 $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/brewberryPi_v2.app.dSYM/Contents/Resources/DWARF/brewberryPi_v2

uninstall_debug_info_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/brewberryPi_v2.app.dSYM/Contents/Resources/DWARF/brewberryPi_v2
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/brewberryPi_v2/bin/brewberryPi_v2.app.dSYM/Contents/Resources/DWARF/ 


install: install_target install_debug_info_plist_target install_debug_info_target  FORCE

uninstall: uninstall_target uninstall_debug_info_plist_target uninstall_debug_info_target  FORCE

FORCE:

